Bulletin_Board/Bulletin_Board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ads/', include('board.urls')),
    path('auth/', include('customers.urls')),
]

Bulletin_Board/board/urls.py
from django.urls import path
from .views import AdsList, AdsCreate, AdsUpdate, ReplyAdd, Replies, delete_reply, delete_ads, \
 allow_reply, news_send
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.AdsList.as_view(), name='ads_list'),
    path('create/', AdsCreate.as_view(), name='create'),
    path('<int:pk>/edit/', AdsUpdate.as_view(), name='ads_edit'),
    path('<int:pk>/reply/add', ReplyAdd.as_view(), name='reply_add'),
    path('replies/', Replies.as_view(), name='replies'),
    path('delete/<int:pk>', delete_reply, name='delete_reply'),
    path('<int:pk>/delete', delete_ads, name='delete_post'),
    path('<int:pk>/allow', allow_reply, name='allow_reply'),
    path('send_mails/', news_send, name='send_mails'),

]

Bulletin_Board/templates/activate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Activation</title>
</head>
<body>
  {% if not user.is_authenticated %}
<div class="container">
<h1 class="text-center">Активировать учетную запись</h1>
    <div class="col-lg-6 col-lg-offset-3">
        <form method="post" action="{% url 'activation' %}">
            {% csrf_token %}
            {% for field in form %}
            <p>
              {{ field.label_tag }}<br>
                {% for error in field.errors %}
                    <p class="register-error">{{ error }}</p>
                {% endfor %}
              {{ field }}
              {% if field.help_text %}
              <span class="help-text-register">{{ field.help_text }}</span>
              {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-success">Активировать</button>
        </form>
    </div>
</div>
{% else %}
<h1 class="text-center">Вы уже зарегистрированы!</h1>
<h5 class="text-center">Чтобы зарегистрировать новый аккаунт, выйдете из текущего.</h5>
{% endif %}
</body>
</html>

Bulletin_Board/templates/ads_create.html

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creating...</title>
</head>
<body>
  <h1>Обьявление</h1>
<form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
</form>
</body>
</html>

Bulletin_Board/templates/ads_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editing...</title>
</head>
<body>
  <h1>Обьявление</h1>
<form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
</form>
</body>
</html>

Bulletin_Board/templates/ads_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Объявления</title>
</head>
<body>
    {% if is_logged %}
        <button><a href="{% url 'board:create' %}">Опубликовать объявление</a></button>
        <button><a href="{% url 'board:replies' %}">Мои отклики</a></button>
        <button><a href="{% url 'logout' %}">Выйти</a></button>
        {% if user_is_staff %}
            <button><a href="{% url 'board:send_mails' %}">Сделать новостную рассылку</a></button>
        {% endif %}
    {% else %}
        <button><a href="{% url 'login' %}">Войти</a></button>
    {% endif %}

    {% if ads %}
    <table align="center" cellspacing=20>
           <tr>
               <th style="font-size:20px">Название</th>
               <th style="font-size:20px">Категория</th>
               <th style="font-size:20px">Содержание</th>
               <th style="font-size:20px">Действия</th>
           </tr>

           {% for ad in ads %}
           <tr>
               <td><a>{{ ad.title }}</a></td>
               <td>{{ ad.category }}</td>
               <td>{{ ad.text|truncatewords:20 }}</td>
               {% if ad.image %}
                    <img src="{{ ad.image.url }}" alt="{{ ad.title }}" />
               {% endif %}

               {% if ad.video %}
                    <video width="320" height="240" controls>
                        <source src="{{ ad.video.url }}" type="video/mp4">
                    </video>
               {% endif %}
               <td>
                   {% if user == ad.author %}
                       <button><a href="{% url 'board:ads_edit' ad.id %}">Редактировать</a></button>
                       <button><a href="{% url 'board:delete_post' ad.id %}">Удалить</a></button>
                   {% endif %}
               </td>
           </tr>
           {% endfor %}
       </table>
    {% else %}
        <h2>Объявлений нет!</h2>
    {% endif %}

</body>
</html>

Bulletin_Board/templates/replies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Replies</title>
</head>
<body>
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input type="submit" value="Найти"/>
    </form>
    {% if filter.qs %}
        {% for reply in filter.qs %}
            <ul>
            <li><strong>{{ reply.author }} {{ reply.date_posted }}&nbsp;
                {% if reply.post.post_author == request.user or reply.author == request.user %}
                    <button><a href="{% url 'delete_reply' reply.id %}">Удалить</a></button>
                {% endif %}
                {% if reply.post.post_author == request.user and not reply.is_allowed %}
                    <button><a href="{% url 'allow_reply' reply.id %}">Принять</a></button>
                {% elif reply.post.post_author == request.user and reply.is_allowed %}
                    (ПРИНЯТО)
                {% endif %}
            </strong></li>
            <li><strong>Обьявление: <a href="{% url 'post' reply.post.id %}">{{ reply.post }}</a></strong>
            <ul>
            <li><em>{{ reply.content }}</em></li>
            </ul>
            </li>
            </ul>
        {% endfor %}
    {% else %}
    <h2>Откликов нет!</h2>
    {% endif %}
</body>
</html>

Bulletin_Board/templates/reply_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reply</title>
</head>
<body>
    <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />

    </form>
</body>
</html>

Bulletin_Board/templates/reply_sendmail_accepted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SendMail</title>
</head>
<body>
    <h2> Ваш отклик принят. Обьявление <a href="{{ ads_link }}">{{ ads_title }}</a> </h2>
    <p>{{ text }}</p>
</body>
</html>

Bulletin_Board/templates/reply_sendmail_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h2> К вашему обьявлению был добавлен новый отклик. </h2>
<p>{{ text }}</p>
</body>
</html>

Bulletin_Board/templates/send_mails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SendMails</title>
</head>
<body>
<h1>Сделайте рассылку которую получат все пользователи</h1>
<form action="{% url 'send_mails' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить"/>
</form>
</body>
</html>

Bulletin_Board/templates/send_mails_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ads</title>
</head>
<body>
    <h1>{{ text }}</h1>
</body>
</html>

Bulletin_Board/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Signup</title>
</head>
<body>
    {% if not user.is_authenticated %}
  <div class="container">
  <h1 class="text-center">Регистрация</h1>
      <div class="col-lg-6 col-lg-offset-3">
          <form method="post" action="{% url 'signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <p>
                {{ field.label_tag }}<br>
                  {% for error in field.errors %}
                      <p class="register-error">{{ error }}</p>
                {% endfor %}
                {{ field }}
                {% if field.help_text %}
                <span class="help-text-register">{{ field.help_text }}</span>
                {% endif %}

              </p>
              {% endfor %}
              <button type="submit" class="btn btn-success">Зарегистрироваться</button>
          </form>
      </div>
  </div>
  {% else %}
  <h1 class="text-center">Вы уже зарегистрированы!</h1>
  <h5 class="text-center">Чтобы зарегистрировать новый аккаунт, выйдете из текущего.</h5>
  {% endif %}
</body>
</html>